src/Entity/Category.php
<?php

namespace App\Entity;

use Assert\NotBlank;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Mime\Message;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: CategoryRepository::class)]
class Category
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    /**
     *@Assert\NotBlank(message="noooooooooooooooon")
     *@Assert\Length(min=3, minMessage ="au moins  3 caractere")
     */
    #[Assert\NotBlank(message: 'Not blank please')]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\OneToMany(mappedBy: 'category', targetEntity: Product::class)]
    private Collection $Products;

    #[ORM\ManyToOne(inversedBy: 'categories')]
    private ?User $id_owner = null;

    public function __construct()
    {
        $this->Products = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection<int, Product>
     */
    public function getProducts(): Collection
    {
        return $this->Products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->Products->contains($product)) {
            $this->Products->add($product);
            $product->setCategory($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->Products->removeElement($product)) {
            // set the owning side to null (unless already changed)
            if ($product->getCategory() === $this) {
                $product->setCategory(null);
            }
        }

        return $this;
    }

    public function getIdOwner(): ?User
    {
        return $this->id_owner;
    }

    public function setIdOwner(?User $id_owner): self
    {
        $this->id_owner = $id_owner;

        return $this;
    }
}

src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ProductRepository;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'Not blank please')]
    private ?string $name = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: 'Not blank please')]
    private ?int $price = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\ManyToOne(inversedBy: 'Products')]
    private ?Category $category = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'Not blank please')]
    private ?string $picture = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $shortDescription = null;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: PurchaseItem::class)]
    private Collection $purchaseItems;



    public function __construct()
    {
        $this->purchaseItems = new ArrayCollection();
    }


    public function revision()
    {
        // public static function loadValidatorMetadata(ClassMetadata $metaData)
        // {
        //     $metaData->addPropertyConstraints('name', [
        //         new NotBlank(['message' => 'le nom de produit est obligatoire']),
        //         new Length(['min' => 3, 'max' => 255, "minMessage" => " Plus que 3 svp"])
        //     ]);

        //     $metaData->addPropertyConstraint(
        //         'price',
        //         new NotBlank(['message' => 'le prix est obligatoire']),
        //     );
        // }
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUpperName(): ?string
    {
        return strtoupper($this->name);
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(?int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getShortDescription(): ?string
    {
        return $this->shortDescription;
    }

    public function setShortDescription(?string $shortDescription): self
    {
        $this->shortDescription = $shortDescription;

        return $this;
    }

    /**
     * @return Collection<int, PurchaseItem>
     */
    public function getPurchaseItems(): Collection
    {
        return $this->purchaseItems;
    }

    public function addPurchaseItem(PurchaseItem $purchaseItem): self
    {
        if (!$this->purchaseItems->contains($purchaseItem)) {
            $this->purchaseItems->add($purchaseItem);
            $purchaseItem->setProduct($this);
        }

        return $this;
    }

    public function removePurchaseItem(PurchaseItem $purchaseItem): self
    {
        if ($this->purchaseItems->removeElement($purchaseItem)) {
            // set the owning side to null (unless already changed)
            if ($purchaseItem->getProduct() === $this) {
                $purchaseItem->setProduct(null);
            }
        }

        return $this;
    }
}

src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Product;
use App\Entity\Category;
use App\Form\Type\PriceType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Validator\Constraints\NotBlank;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                "label" => "Nom de produit",
                "attr" => [
                    "placeholder" => "Tapez le nom de produit "
                ],
                'required' => false,
                'constraints' => new NotBlank(['message' => 'validation de formulaire : nom produit vide'])
            ])
            ->add('shortDescription', TextareaType::class, [
                "label" => "Description courte",
                "attr" => [
                    "placeholder" => "Tapez une desciprtion courte pour le produit pour le visiteur"
                ],
                'required' => false,
                'constraints' => new NotBlank(['message' => 'validation de formulaire : nom produit vide'])
            ])

            //pricetype c'est un type de prix creer 
            ->add('price', PriceType::class, [
                "label" => "Le prix de produit",
                "attr" => [
                    "placeholder" => "prix.."
                ],


                // divise par 100 apres le submit , personnalider sinon on peut utiliser divisor de type MoneyType
                'divide' => 100,
                'required' => false,
                'constraints' => new NotBlank(['message' => 'validation de formulaire : nom produit vide']),
            ])

            ->add('picture', UrlType::class, [
                "label" => "image de produit",
                'attr' => [
                    "placeholder" => "tapez une url d'image "
                ],
                'required' => false,
                'constraints' => new NotBlank(['message' => 'validation de formulaire : nom produit vide'])
            ])

            //entity type faire appel a name comme choice de la base donnees
            ->add('category', EntityType::class, [
                "label" => "Category",
                "placeholder" => "-- Choisir une catégorie --  ",
                "class" => Category::class,
                "choice_label" =>  function (category $category) {;
                    return strtoupper($category->getName());
                }
                // choices c'est les valuer de la liste repmli avec les valeurs de base

            ]);


        // apres l'ajour de prix , le transformer en centimes dans la base 

        // $builder->get('price')->addModelTransformer(new CentimeTransformer);


        // $builder->addEventListener(FormEvents::POST_SUBMIT, function (FormEvent $event) {

        //     $product = $event->getData();

        //     if ($product->getPrice() !== null) {
        //         $product->setPrice($product->getPrice() * 100);
        //     }
        // });

        // $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) {

        //     $form = $event->getForm();

        //     /** @var Product */
        //     $product = $event->getData();

        //     if ($product->getPrice() !== null) {
        //         $product->setPrice($product->getPrice() / 100);
        //     }


        //     if ($product->getId() === null) {


        //         $form->add('category', EntityType::class, [
        //             "label" => "Category",
        //             "placeholder" => "-- Choisir une catégorie --  ",
        //             "class" => Category::class,
        //             "choice_label" =>  function (category $category) {;
        //                 return strtoupper($category->getName());
        //             }

        //         ]);
        //     }
        // });
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
        ]);
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Events\ProductViewEvent;
use App\Form\ProductType;
use App\Repository\ProductRepository;
use App\Repository\CategoryRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\Validator\Validator\ValidatorInterface;

class ProductController extends AbstractController
{
    //affiche les produits d'une categorie
    #[Route('/category/{slug}', name: 'product_category', priority: -1)]
    public function category($slug, CategoryRepository $categoryRepository)
    {
        // cherche par slug les catégories
        $category = $categoryRepository->findOneBy(['slug' => $slug]);

        if (!$category) {
            // envoie un erreur personaliser
            throw $this->createNotFoundException("Catégorie n'existe pas");
        }
        return $this->render('product/category.html.twig', [
            'slug' => $slug,
            'category' => $category,
        ]);
    }

    // affiche les details d'un produit
    #[Route('/product/{slug}', name: 'product_show')]
    public function show($slug, $prenom, ProductRepository $productRepository, EventDispatcherInterface $eventDispatcher)
    {

        $product = $productRepository->findOneBy(['slug' => $slug]);

        if (!$product) {
            throw $this->createNotFoundException("Produit n'existe pas");
        }

        // lancer product View 

        $eventDispatcher->dispatch(new ProductViewEvent($product), 'product.view');

        return $this->render('product/show.html.twig', [
            'product' => $product,
            'slug' => $slug,
        ]);
    }


    //creer un formulaire pour un produit
    #[Route('/admin/product/create', name: 'product_create')]
    public function create(Request $request, SluggerInterface $slugger, EntityManagerInterface $em)
    {
        $product = new Product();

        $form = $this->createForm(ProductType::class, $product);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            // creation de slug dans la base comme le nom de produit 
            $product->setSlug(strtolower($slugger->slug($product->getName())));
            $em->persist($product);
            $em->flush();

            return $this->redirectToRoute('product_show', [
                'slug' => $product->getSlug()
            ]);
        }

        $formView = $form->createView();

        return $this->render(('product/create.html.twig'), [
            'formView' => $formView
        ]);
    }

    //modifier un produit 
    #[Route('/admin/product/{id}/edit', name: 'product_edit')]
    public function edit($id, ProductRepository $productRepository, Request $request, EntityManagerInterface $em, SluggerInterface $slugger)
    {
        // $revision =

        //test de collection 
        // $client = [
        //     'nom' => '',
        //     'prenom' => 'amzyl',
        //     'voiture' => [
        //         'marque' => 'BMW',
        //         'couleur' => ''
        //     ]
        // ];


        // $collection = new Collection([
        //     'nom' => new NotBlank([
        //         'message' => "le nom ne doit pas etre vide"
        //     ]),
        //     'prenom' =>  new NotBlank(['message' => "le prenom ne doit pas etre blank"]),
        //     new Length(['min' => 3, 'minMessage' => 'ne doit pas faire moins de 3 caractere']),


        //     'voiture' => new Collection([
        //         'marque' => new NotBlank(['message' => 'marque obligatoire']),
        //         'couleur' => new NotBlank(['message' => 'couleur est obligatoire'])

        //     ]),
        // ]);


        // $product = new Product();

        // $validator->validate($product);



        //test des donnee scalaire 
        // $age = -10;
        // $result = $validator->validate($age, [new LessThanOrEqual([
        //     'value' => 90,
        //     'message' => "khso ykon na9es ela  {{ compared_value }} mais nta 3titini {{ value }}"
        // ]), new ConstraintsGreaterThan([
        //     'value' => 0,
        //     'message' => "khso ykon kter mn {{ compared_value }} nta 3titini {{ value }} "
        // ])]);

        // if ($result->count() > 0) {
        //     dd("il y'a des erreur", $result);
        // }

        // dd("tout va bien");


        $product = $productRepository->find($id);

        $product = $productRepository->find($id);

        $form = $this->createForm(ProductType::class, $product);



        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            $product->setSlug(strtolower($slugger->slug($product->getName())));

            $em->flush();

            return $this->redirectToRoute('product_show', [
                'slug' => $product->getSlug()
            ]);
        }

        $formView = $form->createView();

        return $this->render(
            'product/edit.html.twig',
            [
                'product' => $product,
                'formView' => $formView
            ]
        );
    }
}

templates/product/_product_cart.html.twig
<div class="card">
	<img src="{{p.picture}}" class="img-fluid" alt="image de produit">
	<div class="card-body">

		<h4 class="card-title">
			{{p.name}}
			, ({{p.price | amount }})
		</h4>
		{# &euro; #}
		<span class="badge alert-warning">{{p.category.name}}</span>

		<p class="card-text">
			{{p.shortDescription}}</p>
		<a href="{{path('product_show' , {'slug':p.slug})}}" class="btn btn-primary btn-sm">
			Details</a>
		<a href="{{path('cart_add' , {'id' : p.id})}}" class="btn btn-success btn-sm">Ajouter
		</a>
	</div>

</div>

templates/product/category.html.twig
{% extends "base.html.twig" %}

{% block title %}
	Catégories :
	{{category.name}}
{% endblock %}

{% block body %}
	<ol class="breadcrumb">
		<li class="breadcrumb-item">
			<a href="{{ path('homepage') }}">Acceuil</a>
		</li>
		<li class="breadcrumb-item">
			<a href="{{path('product_category' , {'slug' : category.slug})}}">{{category.name}}</a>
		</li>

	</ol>

	<h1>
		Catégorie :
		{{category.name}}
	</h1>

	<div class="row">
		{% for p in category.products %}

			<div class="col-4">
				{% include "product/_product_cart.html.twig" %}

			</div>

		{% endfor %}
	</div>
{% endblock %}

templates/product/create.html.twig
{% extends "base.html.twig" %}

{# appeler un theme #}

{# deja declaré dans twig.yaml {% form_theme formView 'bootstrap_4_layout.html.twig'%} #}


	{% block title %}
Création d'un produit
{% endblock %}

	{% block body %}
		<h1>
	Nouveau produit :
	</h1>

	{{form_start(formView)}}
	{{form_errors(formView)}}
		<div class="row"> <div class="col">
			{{form_row(formView.name)}}
			{{form_row(formView.price)}}
		</div>

		<div class="col">

			{{form_row(formView.category)}}
			{{form_row(formView.shortDescription)}}
			{{form_row(formView.picture)}}

		</div>
	</div>

	<button type="submit" class="btn btn-primary mt-1">
		<i class="fas fa-save"></i>
		Créer le produit</button>

	{{form_end(formView)}}

{% endblock %}


{# creation de theme pour les form row #}
{% block form_row %}

	<div class="form-group">
		{{ form_label(form)}}
		{{form_widget(form , {"attr" : {"class":"form-control"}})}}
	</div>

{% endblock %}

templates/product/edit.html.twig
{% extends "base.html.twig" %}

{% block title %}
	Modification de Produit :
	{{product.name}}
{% endblock %}

{% block body %}
	<h1>
		Modification de Produit :
		{{product.name}}
	</h1>

	{{form_start(formView)}}
	{{form_errors(formView)}}
	<div class="row">
		<div class="col">
			{{form_row(formView.name)}}
			{{form_row(formView.price)}}
		</div>

		<div class="col">

			{{form_row(formView.category)}}
			{{form_row(formView.shortDescription)}}
			{{form_row(formView.picture)}}

		</div>
	</div>

	<button type="submit" class="btn btn-primary mt-1">
		<i class="fas fa-save"></i>
		Modifier le produit</button>

	{{form_end(formView)}}


{% endblock %}

templates/product/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProductController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/AmzylMohcine/Desktop/cours-ecommerce/src/Controller/ProductController.php'|file_link(0) }}">src/Controller/ProductController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/AmzylMohcine/Desktop/cours-ecommerce/templates/product/index.html.twig'|file_link(0) }}">templates/product/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/product/show.html.twig
{% extends "base.html.twig" %}

{% block title %}
	{{product.name}}
{% endblock %}

{% block body %}
	{# {{ dump(app.session.getbag('flashes').get('success'))}} #}


	<ol class="breadcrumb">
		<li class="breadcrumb-item">
			<a href="{{ path('homepage') }}">Acceuil</a>
		</li>
		<li class="breadcrumb-item active">{{product.name}}</li>
	</ol>
	<h1>
		{{product.name}}
		({{product.price | amount }}
		)
	</h1>


	<div class="row pt-4">
		<div class="col-2">
			<img class="img-fluid" src="{{product.picture}}" alt="image de {{product.name}} ">
		</div>
		<div class="col">
			<a href="{{ path ('product_category' , {'slug' : product.category.slug})}}">
				<span class="badge alert-primary">
					{{product.category.name}}
				</span>
			</a>
			<p>{{product.shortDescription}}
			</p>
			<a href="{{ path('cart_add' , {'id':product.id})}}" class="btn btn-success btn-lg">
				<i class="fas fa-shopping-cart"></i>
				Ajouter au panier
			</a>
		</div>

	</div>
{% endblock %}